import NavBar from '@/components/NavBar/NavBar';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import useSWR from 'swr';

const inter = Inter({ subsets: ['latin'] })

type Devices = {
  product: {
    name: string;
  };
  id: string;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <NavBar />
      {/* Search */}
      {/* CardContainer */}
      {/* <body className={inter.className}>{children}</body> */}
    </>
  )
}
